# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_vaidya_samples <- function(n, initial, A, b, r) {
    .Call(`_gausspolytopewalk_generate_vaidya_samples`, n, initial, A, b, r)
}

