# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_john_samples <- function(n, burnin, initial, A, b, r, lazy) {
    .Call(`_gausspolytopewalk_generate_john_samples`, n, burnin, initial, A, b, r, lazy)
}

generate_vaidya_samples <- function(n, burnin, initial, A, b, r, lazy) {
    .Call(`_gausspolytopewalk_generate_vaidya_samples`, n, burnin, initial, A, b, r, lazy)
}

